### ISSUE TITLE
谢谢这个脚本 未来不知道能否加个聊天居中 哈哈 

### ISSUE THREAD

**Issue by ROSN5151** [zhangnew/bing-chat-script#1]

**Comment by zhangnew** [comment]
为什么？感觉这个需求过于个性化，可以考虑自己用 [stylus](https://github.com/openstyles/stylus/) 修改一下 css

**Comment by 1353604736** [comment]
我也有类似需求，就是不知道怎么用css，居中对宽屏友好，不然总是扭头看

**Comment by zhangnew** [comment]
安装 [stylus](https://github.com/openstyles/stylus/) 之后再安装如下样式即可：

https://userstyles.world/style/10973/bing-chat

样式里面只有两个数字，我没有在其他屏幕测试，自己可以随意修改看效果
