### ISSUE TITLE
不會自動複製最後一個問題並黏貼到下一次問答中

### ISSUE THREAD

**Issue by willy99924** [zhangnew/bing-chat-script#2]

**Comment by zhangnew** [comment]
更新试试

**Comment by willy99924** [comment]
> 更新試試
更新後按enter不發送回答改成換行的功能沒了
英文好像有內建但中文沒有

**Comment by zhangnew** [comment]
> > 更新試試
> > 更新後按enter不發送回答改成換行的功能沒了
> > 英文好像有內建但中文沒有

shift + enter 是换行，enter 是发送
