### ISSUE TITLE
Can you add quick link support?

### ISSUE THREAD

**Issue by bigplayer-ai** [zhangnew/bing-chat-script#3]
Hey,
Can you add Instantly prompts BingChat based on the provided query in URL search params. For instance, https://www.bing.com/chat?prompt="Who is Harry Potter" will instantly prompt BingChat with "Who is Harry Potter"

**Comment by zhangnew** [comment]
try https://github.com/zhangnew/bing-chat-script/releases/tag/v0.0.5
